spring.application.name=CollectionRequirementsB2-test

#spring.datasource.url=jdbc:h2:mem:dev
spring.datasource.url=jdbc:h2:file:./data/test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=test

#    h2 database console
spring.h2.console.enabled=true

#    hibernate set-up
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect